config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: redirect('/contacts')

  resources :contacts, except: :show do
    get 'search', to: 'contacts#search', on: :collection, as: :search
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  validates :first_name, :last_name, :phone_number, presence: true

  scope :ordered_by_last_name, -> { order(last_name: :asc) }
  scope :search, ->(last_name) { where('last_name LIKE ?', "%#{last_name}%") }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :set_contact, only: %i[edit update destroy]

  def index
    @contacts = Contact.ordered_by_last_name
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contacts_path, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @contact.update(contact_params)
      redirect_to contacts_path, notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @contact.destroy

    redirect_to contacts_path, notice: t('.success')
  end

  def search
    @contacts = Contact.search(params[:last_name]).ordered_by_last_name

    render :index
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phone_number)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def item_borders(collection_counter, collection_size)
    if collection_size == 1 || collection_counter.zero?
      'border'
    else
      'border-l border-r border-b'
    end
  end

  def item_rounded_corners(collection_counter, collection_size)
    if collection_counter.zero?
      'rounded-t'
    elsif collection_counter == collection_size - 1
      'rounded-b'
    end
  end
end

app/views/contacts/_contact.html.erb
<% borders = item_borders(contact_counter, contact_iteration.size) %>
<% rounded_corners = item_rounded_corners(contact_counter, contact_iteration.size) %>

<div class="flex items-center justify-between px-6 py-4 bg-white border-gray-300 <%= borders %> <%= rounded_corners %>">
  <div class="space-y-2">
    <span class="font-bold text-lg"><%= link_to contact.full_name, edit_contact_path(contact) %></span>

    <div class="flex items-center space-x-2 text-gray-500">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
        <path fill-rule="evenodd" d="M2 3.5A1.5 1.5 0 013.5 2h1.148a1.5 1.5 0 011.465 1.175l.716 3.223a1.5 1.5 0 01-1.052 1.767l-.933.267c-.41.117-.643.555-.48.95a11.542 11.542 0 006.254 6.254c.395.163.833-.07.95-.48l.267-.933a1.5 1.5 0 011.767-1.052l3.223.716A1.5 1.5 0 0118 15.352V16.5a1.5 1.5 0 01-1.5 1.5H15c-1.149 0-2.263-.15-3.326-.43A13.022 13.022 0 012.43 8.326 13.019 13.019 0 012 5V3.5z" clip-rule="evenodd" />
      </svg>

      <span class="font-bold"><%= contact.phone_number %></span>
    </div>
  </div>

  <%= link_to contact_path(contact), data: { turbo_method: :delete, turbo_confirm: t('.remove_confirmation') }, class: 'p-2 rounded bg-red-500' do %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-white">
      <path fill-rule="evenodd" d="M16.5 4.478v.227a48.816 48.816 0 013.878.512.75.75 0 11-.256 1.478l-.209-.035-1.005 13.07a3 3 0 01-2.991 2.77H8.084a3 3 0 01-2.991-2.77L4.087 6.66l-.209.035a.75.75 0 01-.256-1.478A48.567 48.567 0 017.5 4.705v-.227c0-1.564 1.213-2.9 2.816-2.951a52.662 52.662 0 013.369 0c1.603.051 2.815 1.387 2.815 2.951zm-6.136-1.452a51.196 51.196 0 013.273 0C14.39 3.05 15 3.684 15 4.478v.113a49.488 49.488 0 00-6 0v-.113c0-.794.609-1.428 1.364-1.452zm-.355 5.945a.75.75 0 10-1.5.058l.347 9a.75.75 0 101.499-.058l-.346-9zm5.48.058a.75.75 0 10-1.498-.058l-.347 9a.75.75 0 001.5.058l.345-9z" clip-rule="evenodd" />
    </svg>
  <% end %>
</div>

app/views/contacts/_form.html.erb
<div class="space-y-1">
  <%= form.label :first_name, class: 'font-bold' %>
  <%= form.text_field :first_name, required: true, class: 'input-field w-full lg:w-auto' %>
</div>

<div class="space-y-1">
  <%= form.label :last_name, class: 'font-bold' %>
  <%= form.text_field :last_name, required: true, class: 'input-field w-full lg:w-auto' %>
</div>

<div class="space-y-1">
  <%= form.label :phone_number, class: 'font-bold' %>
  <%= form.phone_field :phone_number, required: true, class: 'input-field w-full lg:w-auto' %>
</div>

<div class="pt-6">
  <%= form.submit t('.submit'), class: 'btn btn-primary w-full lg:w-auto cursor-pointer' %>
</div>

app/views/contacts/_search.html.erb
<%= form_with url: search_contacts_path, method: :get, class: 'mt-8' do |form| %>
  <div class="relative mt-2 rounded-md shadow-sm">
    <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5 text-gray-400">
        <path fill-rule="evenodd" d="M10.5 3.75a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM2.25 10.5a8.25 8.25 0 1114.59 5.28l4.69 4.69a.75.75 0 11-1.06 1.06l-4.69-4.69A8.25 8.25 0 012.25 10.5z" clip-rule="evenodd" />
      </svg>
    </div>

    <%= form.text_field :last_name, value: params[:last_name],placeholder: t('.placeholder'), class: 'input-field pl-10 w-full' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="flex space-x-2">
  <%= link_to contacts_path do %>
    <h2 class="font-semibold text-xl lg:text-3xl"><%= t('contacts.index.title') %></h2>
  <% end %>
  <span class="font-semibold text-xl lg:text-3xl">&gt;</span>
  <h2 class="font-semibold text-xl lg:text-3xl"><%= @contact.full_name %></h2>
</div>

<%= render 'shared/errors', object: @contact if @contact.errors.any? %>

<%= form_with model: @contact, url: contact_path(@contact), method: :put, class: 'mt-8 space-y-4' do |form| %>
  <%= render 'form', form: form %>
<% end %>

app/views/contacts/index.html.erb
<div class="flex justify-between">
  <%= link_to contacts_path do %>
    <h2 class="font-semibold text-xl lg:text-3xl"><%= t('.title') %></h2>
  <% end %>

  <%= link_to t('.add'), new_contact_path, class: 'btn btn-primary' %>
</div>

<%= render 'search' %>

<div class="mt-8">
  <% if @contacts.any? %>
    <%= render @contacts %>
  <% else %>
    <div class="mt-16 mb-10 text-center">
      <span class="text-gray-500"><%= t('.no_contacts') %></span>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="flex space-x-2">
  <%= link_to contacts_path do %>
    <h2 class="font-semibold text-xl lg:text-3xl"><%= t('contacts.index.title') %></h2>
  <% end %>
  <span class="font-semibold text-xl lg:text-3xl">&gt;</span>
  <h2 class="font-semibold text-xl lg:text-3xl"><%= t('.title') %></h2>
</div>

<%= render 'shared/errors', object: @contact if @contact.errors.any? %>

<%= form_with model: @contact, url: contacts_path, class: 'mt-8 space-y-4' do |form| %>
  <div class="space-y-1">
    <%= form.label :first_name, class: 'font-bold' %>
    <%= form.text_field :first_name, class: 'input-field w-full lg:w-auto' %>
  </div>

  <div class="space-y-1">
    <%= form.label :last_name, class: 'font-bold' %>
    <%= form.text_field :last_name, required: true, class: 'input-field w-full lg:w-auto' %>
  </div>

  <div class="space-y-1">
    <%= form.label :phone_number, class: 'font-bold' %>
    <%= form.phone_field :phone_number, required: true, class: 'input-field w-full lg:w-auto' %>
  </div>

  <div class="pt-6">
    <%= form.submit t('.submit'), class: 'btn btn-primary w-full lg:w-auto' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="bg-gray-50 py-8 mx-auto lg:max-w-5xl">
      <%= link_to contacts_path do %>
        <h1 class="font-semibold text-3xl lg:text-5xl flex gap-x-5 items-center justify-center">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 h-10 lg:w-14 lg:h-14">
            <path fill-rule="evenodd" d="M4.5 3.75a3 3 0 00-3 3v10.5a3 3 0 003 3h15a3 3 0 003-3V6.75a3 3 0 00-3-3h-15zm4.125 3a2.25 2.25 0 100 4.5 2.25 2.25 0 000-4.5zm-3.873 8.703a4.126 4.126 0 017.746 0 .75.75 0 01-.351.92 7.47 7.47 0 01-3.522.877 7.47 7.47 0 01-3.522-.877.75.75 0 01-.351-.92zM15 8.25a.75.75 0 000 1.5h3.75a.75.75 0 000-1.5H15zM14.25 12a.75.75 0 01.75-.75h3.75a.75.75 0 010 1.5H15a.75.75 0 01-.75-.75zm.75 2.25a.75.75 0 000 1.5h3.75a.75.75 0 000-1.5H15z" clip-rule="evenodd" />
          </svg>

          <%= t('global.app_title') %>
        </h1>
      <% end %>

      <div class="px-12 pt-10 lg:pt-16">
        <% flash.each do |key, value| %>
          <%= render 'shared/flash', key: key, value: value %>
        <% end %>

        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<div class="bg-red-50 text-red-500 px-3 py-2 rounded-lg mt-3">
  <ul>
    <% object.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_flash.html.erb
<div class="rounded-md p-4 mb-5 bg-green-50">
  <div class="flex items-center space-x-2">
    <div class="flex-shrink-0">
      <!-- Heroicon name: solid/check-circle -->
      <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
      </svg>
    </div>

    <p class="text-sm text-green-700"><%= value.html_safe %></p>
  </div>
</div>